service: undefined-meetup

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  environment:
    ENVIRONMENT: ${opt:stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"


functions:
  api:
    handler: handlers.handler
    events:
      - http:
          path: /{proxy+}
          method: any
